logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- })
                  {magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}
                  %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    ROOT: info
    org.apache.kafka.clients: info
    org.springframework.kafka: debug


spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  application:
    name: java-reliable-producer

  kafka:

    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    template:
      default-topic: session-five-topic
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9093
